# Data Analysis Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [3]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1,2,3]
l_2 = [4,5,6]

print(f'Sum of {l_1} + {l_2} using python operators in one line: {l_1 + l_2}')
# print(f'Sum of {l_1} + {l_2} using python operators in one line: {l_1 - l_2}')


Sum of [1, 2, 3] + [4, 5, 6] using python operators in one line: [1, 2, 3, 4, 5, 6]


<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [5]:
list1 = [2, 3, 4]
list2 = [1, 5, 2]
answer = []

for i in range(len(list1)):
    answer.append(list1[i] + list2[i])  
print(answer)

[3, 8, 6]


#### Importing

In [6]:
# always import as np, standard across all of data science/analysis
# !pip install numpy
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [9]:
arr_1 = [0,1,2,3]

new_arr = np.array(arr_1)

print(arr_1)
print(new_arr)

[0, 1, 2, 3]
[0 1 2 3]


###### - np.zeros()

In [13]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeros = np.zeros((3,3))
print(arr_zeros)
type(arr_zeros[0][0])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


numpy.float64

###### - np.ones()

In [17]:
arr_ones = np.ones((3,3), int)
arr_ones_def = np.ones((3,3))
print(arr_ones)
print(arr_ones_def)

# notice no dots after the numbers, because we specified the datatype to be integer

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


###### - np.arange()

In [18]:
arr_range = np.arange(1,10)
arr_range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

###### - Making Lists into NDArrays

In [22]:
some_list = [99,14,7]
numpy_array = np.array(some_list)
print(numpy_array)


np_arr_2 = np.array([99,14,7])
print(np_arr_2)

[99 14  7]
[99 14  7]


#### Performing Calculations on NDArrays

###### - Summation

In [24]:
np_list = np.array([5,10,15,20,25,30])
np_list_2 = np.array([10,20,30,40,50,60])

result_sum = np_list + np_list_2
result_sum

array([15, 30, 45, 60, 75, 90])

###### - Difference

In [25]:
result_diff = np_list_2 - np_list
result_diff

array([ 5, 10, 15, 20, 25, 30])

###### - Multiplication

In [26]:
result_prod = np_list * np_list_2
result_prod

array([  50,  200,  450,  800, 1250, 1800])

###### - Division

In [28]:
result_div = np_list_2 / np_list
result_div

array([2., 2., 2., 2., 2., 2.])

#### Modulo

In [31]:
result_mod = np_list % np_list_2
result_mod

array([ 5, 10, 15, 20, 25, 30], dtype=int32)

#### Floor Division

In [35]:
result_floor = np_list // np_list_2
print(result_floor)

[0 0 0 0 0 0]
[    9765625  1661992960 -1905200863           0 -1971132175           0]


#### Numpy Subsetting

In [63]:
# result3 <= 800
print(result_prod)
print(result_prod <= 800)


test_ndStrings = np.array(['Bob','Mark','Jessica','Barb'])
print(test_ndStrings[test_ndStrings == 'Bob'])

# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition

np.array([name for name in test_ndStrings if name[0] == 'B'])

[  50  200  450  800 1250 1800]
[ True  True  True  True False False]
['Bob']


array(['Bob', 'Barb'], dtype='<U4')

#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [66]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList, cList]
print(M)


print(M[2][0])

# second step: place Matrix inside NDArray
ND_M = np.array(M)
print(ND_M)



[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
6
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [67]:
# in order to grab the 0th index from the 3rd row
ND_M[2,0]

6

#### Assigning Values in NDArrays

In [68]:
# Changing/assigning value
ND_M[2,0] = 10
ND_M

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10,  7,  8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [69]:
# using the .dtype method
nd_type = ND_M.dtype
nd_type

dtype('int32')

#### Altering NDArray Type

In [72]:
print(nd_type)

# creating new array and changing data type
changed = ND_M.astype(np.float32)

# dtype of new matrix is float32
changed.dtype
changed

int32


array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [10.,  7.,  8.]], dtype=float32)

In [ ]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [75]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
print(changed.shape)
print(ND_M.shape)
# Using the method .shape

# print(type(result_changed.shape))

(3, 3)
(3, 3)


#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [79]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

print(changed)
# (9,1) == 9 rows , 1 column

changed.reshape(9,1)


[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [10.  7.  8.]]


array([[ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [10.],
       [ 7.],
       [ 8.]], dtype=float32)

In [80]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)
print(changed.reshape(9,1))
print(changed.reshape(1,9))

[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [10.]
 [ 7.]
 [ 8.]]
[[ 0.  1.  2.  3.  4.  5. 10.  7.  8.]]


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [83]:
"""
OUTPUT
    array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
"""


mylist = np.arange(0,16)
MYMATRIX = np.arange(0,16)
final = MYMATRIX.reshape(4,4)
final

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Complex Indexing & Assinging

In [110]:
M2 = np.zeros((6,6), int)
print(M2)

# Set every first element in each row to 1
M2[:,0] = 1
print('\n',M2)

# Set all elements in axis 3 to 5 (Excluding 5) to be equal to the number 5
M2[3:5, :] = 5
print('\n',M2)

# reset the matrix back to 0
M2 = M2 * 0
print('\n',M2)

# Set the second and third columns to a number == 2
M2[:, 2:4] = 2
print('\n',M2)

# Creating a vector in numpy
x = np.arange(6)
print('\n',x)
# Reset the Matrix to 0
M2 = M2 * 0
print('\n',M2)
# Set the first row to that range of vector numbers we just created
M2[:,0] = x
print('\n',M2)

#################
# M[rows,columns]
#################

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

 [[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]

 [[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [5 5 5 5 5 5]
 [5 5 5 5 5 5]
 [1 0 0 0 0 0]]

 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

 [[0 0 2 2 0 0]
 [0 0 2 2 0 0]
 [0 0 2 2 0 0]
 [0 0 2 2 0 0]
 [0 0 2 2 0 0]
 [0 0 2 2 0 0]]

 [0 1 2 3 4 5]

 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]


#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [115]:
# Initialize a vector of range 6, then reset Matrix to zero and run vector multiplication on the matrix
v = M2[:,:]
v = v*0
print(v)

# changing bottow row to 2
v[5, :] = 2
# Reset the Matrix to 0
new = M2* v
new

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [10,  0,  0,  0,  0,  0]])

#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [118]:
new_arr = np.array([400,500,600,700])
print(new_arr)
print(np.where(new_arr < 600))
# Transform Data based on boolean mask == True

new_arr[np.where(new_arr < 600)] == 400

# subsetting syntax
new_arr[new_arr < 600] == 400



[400 500 600 700]
(array([0, 1], dtype=int64),)


array([ True, False])

#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [117]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.7938789871352214
Here is a random number between 0 and 1 Million: 653855.1578236134
Here are 5 random numbers between 0 and 10: [0.15397902 6.28712901 4.53507904 9.35881848 7.33602869]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[4.49392427 0.9883087  0.35031923]
 [7.72731955 7.43893647 2.23911418]
 [9.7815596  7.72249752 8.63148459]]


## Working With CSV's

#### Imports

In [119]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [125]:
# Creating Function to open and read CSV data
def open_csv(filepath, d = ','):
    data = []
    
    with open(filepath, encoding = 'utf-8') as myData:
#         use csv reader from docs to parse through comma sep values
        info = csv.reader(myData, delimiter = d)
        print(info)
#         loop over and append into data list
        for row in info:
            data.append(row)
    return data

# use our function to open marathon 2017
# csv_data = open_csv("../files/boston_marathon2017_edited.csv")
# csv_data[1:5]

#### Loading a CSV's Data 

In [136]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

# i = integer, f = float, |s25 = string with 25 characters
DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

# instead of loading csv normally, let's load it into a numpy array to calculate results on
def load_data(filepath, d = ','):
    data = np.genfromtxt(filepath, delimiter = d, skip_header=1, usecols=np.arange(0,24), 
                         invalid_raise=False, names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../files/redsox_2017_hitting.txt')

# names = bs2017["Name"]
# hits = bs2017["H"]
# for i in range(len(names)):
#     print(f'{names[i]} had {hits[i]} hits')

print(bs2017["H"])

[ 94 125 119 156  63 155 118 166 120  61  57  36  53  28  24  21  20  15
  16   9   1   1   1]


#### Summing the top 5 hitters for HR's

In [145]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all Player Names
# Step 3: Create new list for new_names (empty to start)
# Step 4: Decode the player names into regular strings
# Step 5: Grab all data and place inside of a zipped list
# Step 6: Sort values based on HR data

# Step 1
home_runs = bs2017["HR"]

# Step 2
player_names = bs2017["Name"]

# Step 3
new_names = []

# Step 4
for name in player_names:
    new_names.append(name.decode('utf-8'))
# print(new_names)
# Step 5
zipped_values = list(zip(new_names,home_runs))
# zipped_values = []
# for i in range(len(new_names)):
#     zipped_values.append((new_names[i],home_runs[i]))
# print(zipped_values)

# print(zipped_values)

# Step 6
sorted_hr = sorted(zipped_values, key = lambda x: x[1], reverse=True)
print(sorted_hr[0:6])

[('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Mitch Moreland', 22), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17), ('Xander Bogaerts', 10)]


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>